version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto --go_out=gen --go_opt=paths=source_relative --go-grpc_out=gen --go-grpc_opt=paths=source_relative proto/service.proto
  generateweb:
    aliases:
      - genweb
    desc: "Generate code from proto for web"
    cmds:
      - protoc -I=proto --js_out=import_style=commonjs:./gen --grpc-web_out=import_style=typescript,mode=grpcwebtext:./gen proto/service.proto
